name: auto-build-and-push
run-name: Build and push to ghcr.io 
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GHCR
        run: |
          docker login --username k1d77a --password ${{ secrets.PAT }} ghcr.io 
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./sbcl.ql-and-slynk/Dockerfile
          push: true
          tags: k1d77a/sbcl.ql-and-slynk:latest

