name: auto-build-and-push
run-name: Build and push to ghcr.io 
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:sbcl.ql-and-slynk"
          push: true
          tags: k1d77a/sbcl.ql-and-slynk:latest
          

